#!/bin/bash

TERRAFORM_DOCKER_IMAGE="hashicorp/terraform:full"

AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key) 
AWS_DEFAULT_REGION=$(aws configure get region)

# argument should be init, apply, delete
docker run -i -t --rm \
    -v `pwd`:/data --workdir=/data \
 	-e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
 	-e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
 	-e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
	${TERRAFORM_DOCKER_IMAGE} $@